### ISSUE TITLE
watchFuture tanks performance

### ISSUE THREAD

**Issue by alexanderameye** [escamoteur/watch_it#13]
Hello,

I have this function that returns a future of whether a species is favorited by the user.  (The favorite status is stored on the device in a local database, Isar)

<img width="462" alt="image" src="https://github.com/escamoteur/watch_it/assets/5512569/ba68e082-c1b7-48fe-8cce-eab27428e04b">

I then have a widget like this where the favorite status is watched using `watchFuture` inside of the `build` method. The favorite status is then used in the widget to show an icon (not shown in image)

<img width="484" alt="image" src="https://github.com/escamoteur/watch_it/assets/5512569/9d211137-96f8-48f9-950b-ad708b4b03cd">

This works functionally, and when I remove the favorite status manually, the UI is instantly updated.

However, this completely tanks performance: I see that the widgets are rebuilt every frame.

<img width="484" alt="image" src="https://github.com/escamoteur/watch_it/assets/5512569/bd09e66f-8ebc-44bf-ae50-d0136be708a7">

I understand that a rebuild needs to happen so that the widget can be instantly updated to show the new favorited status.

But how can I improve the performance?

I'm thinking that only really the favorite status widget needs to be rebuilt (I use a ChoiceChip to display the favorite status)

<img width="484" alt="image" src="https://github.com/escamoteur/watch_it/assets/5512569/1329fa40-e6a4-4a02-97dd-8a3d8d2d2f3d">

But the rest of the widgets should not be rebuilt? How can I achieve this?

Should I move the ChoiceChip to its own widget, call `watchFuture` only there in the `build` method so that the other widgets do not need to be rebuilt?

I'm pretty new to flutter and state management so any advice would be great. Or if there is a better way to use watch_it to achieve this, basically my use case seems pretty common.

Thanks a lot!

**Comment by escamoteur** [comment]
I think your problems has different aspects

1. yes putting the Chip into its own widget would only rebuild that widget which would improve performance.
2. The bigger problem in my opinion is that you get e new future on every rebuild because you call that function that calls into  ISAR.

Doesn't ISAR also offer a Stream based API that would send a new data item whenever its data changes? Futures are great for one time calls but not for observing an object

otherwise I would recommend adding a business logic layer in between that checks the status of that field in regular intervalls and then updates a ValueListenable that then is watched by watchValue.

I hope that helps :-)
