### ISSUE TITLE
Cannot register handler for ChangeNotifiers

### ISSUE THREAD

**Issue by smjxpro** [escamoteur/watch_it#19]
I have a _Counter_ class:

```
class Counter extends ChangeNotifier {
        int _count = 0;
        int get count=>_count;

        void increment(){
              _count++;
             notifyListeners();
       }
}
```

Now I want to show a dialog when the value of the `count` becomes greater than 5. 
Therefore I want to register a handler in the build method like:

```
  Widget build(BuildContext context) {
    registerHandler(
        select: (Counter c) => c.count,
        handler: (context, value, cancel) => showNameDialog(context, value));
    ...
  }
```

But it says _count is not a ValueListenable as required by the context_ or something like that. I can watch it though.

It is cumbersome to wrap every variable in a `ValueListenable`. And because we can watch it we should also be able to register handlers for it.

**Comment by escamoteur** [comment]
Ah, I see, you can watch it because the parent class implements ChangeNotifiers otherwise you would not be able to watch it.
Not sure how a registerHandler would look like in such a case. It would need a selector.
Unfortunately Dart doesn't support method oveoading, so we need another name for such a function.
Am 5. Dez. 2023, 15:04 +0100 schrieb S. M. JAHANGIR ***@***.***>:

**Comment by smjxpro** [comment]
Maybe `registerChangeNotifierHandler`?
